// GENERATED by tools/gen_webidl_interfaces.py -- do not edit by hand.
//
// Shape-only WebIDL interface objects. Every one of these is an interface
// Chrome refuses to construct ("Illegal constructor"), so no instance can
// exist and no member can ever be invoked. The observable surface is the
// shape alone -- constructor name/arity, prototype member names and their
// descriptors, prototype parent, statics -- and that is what this reproduces.
//
// These are NOT implementations. See the generator for the reasoning and for
// what has to change if any of them becomes constructible.

const js = @import("../js/js.zig");

// Dead member bodies. Unreachable by construction: reaching them would need an
// instance, and the constructor throws. The types are irrelevant for the same
// reason -- only the descriptor shape they produce is observable.
fn deadGet(comptime T: type) fn (*const T) ?u32 {
    return struct {
        fn get(_: *const T) ?u32 {
            return null;
        }
    }.get;
}

fn deadSet(comptime T: type) fn (*T, ?u32) void {
    return struct {
        fn set(_: *T, _: ?u32) void {}
    }.set;
}

fn deadCall(comptime T: type) fn (*const T) void {
    return struct {
        fn call(_: *const T) void {}
    }.call;
}

fn deadStatic() fn () void {
    return struct {
        fn call() void {}
    }.call;
}

pub const AnimationTimeline = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(AnimationTimeline);

        pub const Meta = struct {
            pub const name = "AnimationTimeline";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const currentTime = bridge.accessor(deadGet(AnimationTimeline), null, .{});
        pub const duration = bridge.accessor(deadGet(AnimationTimeline), null, .{});
    };
};

pub const AudioSinkInfo = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(AudioSinkInfo);

        pub const Meta = struct {
            pub const name = "AudioSinkInfo";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const @"type" = bridge.accessor(deadGet(AudioSinkInfo), null, .{});
    };
};

pub const AuthenticatorResponse = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(AuthenticatorResponse);

        pub const Meta = struct {
            pub const name = "AuthenticatorResponse";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const clientDataJSON = bridge.accessor(deadGet(AuthenticatorResponse), null, .{});
    };
};

pub const BackgroundFetchRecord = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(BackgroundFetchRecord);

        pub const Meta = struct {
            pub const name = "BackgroundFetchRecord";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const request = bridge.accessor(deadGet(BackgroundFetchRecord), null, .{});
        pub const responseReady = bridge.accessor(deadGet(BackgroundFetchRecord), null, .{});
    };
};

pub const BluetoothUUID = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(BluetoothUUID);

        pub const Meta = struct {
            pub const name = "BluetoothUUID";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const canonicalUUID = bridge.function(deadStatic(), .{ .static = true, .arity = 1, .noop = true });
        pub const getCharacteristic = bridge.function(deadStatic(), .{ .static = true, .arity = 1, .noop = true });
        pub const getDescriptor = bridge.function(deadStatic(), .{ .static = true, .arity = 1, .noop = true });
        pub const getService = bridge.function(deadStatic(), .{ .static = true, .arity = 1, .noop = true });
    };
};

pub const CSSStyleValue = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(CSSStyleValue);

        pub const Meta = struct {
            pub const name = "CSSStyleValue";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const toString = bridge.function(deadCall(CSSStyleValue), .{ .arity = 0, .noop = true });

        pub const parse = bridge.function(deadStatic(), .{ .static = true, .arity = 2, .noop = true });
        pub const parseAll = bridge.function(deadStatic(), .{ .static = true, .arity = 2, .noop = true });
    };
};

pub const Credential = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(Credential);

        pub const Meta = struct {
            pub const name = "Credential";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const id = bridge.accessor(deadGet(Credential), null, .{});
        pub const @"type" = bridge.accessor(deadGet(Credential), null, .{});

        pub const isConditionalMediationAvailable = bridge.function(deadStatic(), .{ .static = true, .arity = 0, .noop = true });
    };
};

pub const CropTarget = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(CropTarget);

        pub const Meta = struct {
            pub const name = "CropTarget";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const fromElement = bridge.function(deadStatic(), .{ .static = true, .arity = 1, .noop = true });
    };
};

pub const DOMRectList = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(DOMRectList);

        pub const Meta = struct {
            pub const name = "DOMRectList";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const item = bridge.function(deadCall(DOMRectList), .{ .arity = 1, .noop = true });
        pub const length = bridge.accessor(deadGet(DOMRectList), null, .{});
    };
};

pub const DelegatedInkTrailPresenter = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(DelegatedInkTrailPresenter);

        pub const Meta = struct {
            pub const name = "DelegatedInkTrailPresenter";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const presentationArea = bridge.accessor(deadGet(DelegatedInkTrailPresenter), null, .{});
        pub const updateInkTrailStartPoint = bridge.function(deadCall(DelegatedInkTrailPresenter), .{ .arity = 2, .noop = true });
    };
};

pub const External = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(External);

        pub const Meta = struct {
            pub const name = "External";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const AddSearchProvider = bridge.function(deadCall(External), .{ .arity = 0, .noop = true });
        pub const IsSearchProviderInstalled = bridge.function(deadCall(External), .{ .arity = 0, .noop = true });
    };
};

pub const FencedFrameConfig = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(FencedFrameConfig);

        pub const Meta = struct {
            pub const name = "FencedFrameConfig";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const setSharedStorageContext = bridge.function(deadCall(FencedFrameConfig), .{ .arity = 1, .noop = true });
    };
};

pub const FetchLaterResult = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(FetchLaterResult);

        pub const Meta = struct {
            pub const name = "FetchLaterResult";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const activated = bridge.accessor(deadGet(FetchLaterResult), null, .{});
    };
};

pub const FragmentDirective = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(FragmentDirective);

        pub const Meta = struct {
            pub const name = "FragmentDirective";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };
    };
};

pub const GPUBindGroup = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPUBindGroup);

        pub const Meta = struct {
            pub const name = "GPUBindGroup";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const label = bridge.accessor(deadGet(GPUBindGroup), deadSet(GPUBindGroup), .{});
    };
};

pub const GPUBindGroupLayout = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPUBindGroupLayout);

        pub const Meta = struct {
            pub const name = "GPUBindGroupLayout";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const label = bridge.accessor(deadGet(GPUBindGroupLayout), deadSet(GPUBindGroupLayout), .{});
    };
};

pub const GPUCommandBuffer = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPUCommandBuffer);

        pub const Meta = struct {
            pub const name = "GPUCommandBuffer";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const label = bridge.accessor(deadGet(GPUCommandBuffer), deadSet(GPUCommandBuffer), .{});
    };
};

pub const GPUCompilationInfo = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPUCompilationInfo);

        pub const Meta = struct {
            pub const name = "GPUCompilationInfo";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const messages = bridge.accessor(deadGet(GPUCompilationInfo), null, .{});
    };
};

pub const GPUComputePipeline = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPUComputePipeline);

        pub const Meta = struct {
            pub const name = "GPUComputePipeline";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const getBindGroupLayout = bridge.function(deadCall(GPUComputePipeline), .{ .arity = 1, .noop = true });
        pub const label = bridge.accessor(deadGet(GPUComputePipeline), deadSet(GPUComputePipeline), .{});
    };
};

pub const GPUDeviceLostInfo = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPUDeviceLostInfo);

        pub const Meta = struct {
            pub const name = "GPUDeviceLostInfo";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const message = bridge.accessor(deadGet(GPUDeviceLostInfo), null, .{});
        pub const reason = bridge.accessor(deadGet(GPUDeviceLostInfo), null, .{});
    };
};

pub const GPUError = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPUError);

        pub const Meta = struct {
            pub const name = "GPUError";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const message = bridge.accessor(deadGet(GPUError), null, .{});
    };
};

pub const GPUExternalTexture = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPUExternalTexture);

        pub const Meta = struct {
            pub const name = "GPUExternalTexture";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const label = bridge.accessor(deadGet(GPUExternalTexture), deadSet(GPUExternalTexture), .{});
    };
};

pub const GPUPipelineLayout = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPUPipelineLayout);

        pub const Meta = struct {
            pub const name = "GPUPipelineLayout";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const label = bridge.accessor(deadGet(GPUPipelineLayout), deadSet(GPUPipelineLayout), .{});
    };
};

pub const GPURenderBundle = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPURenderBundle);

        pub const Meta = struct {
            pub const name = "GPURenderBundle";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const label = bridge.accessor(deadGet(GPURenderBundle), deadSet(GPURenderBundle), .{});
    };
};

pub const GPURenderPipeline = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPURenderPipeline);

        pub const Meta = struct {
            pub const name = "GPURenderPipeline";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const getBindGroupLayout = bridge.function(deadCall(GPURenderPipeline), .{ .arity = 1, .noop = true });
        pub const label = bridge.accessor(deadGet(GPURenderPipeline), deadSet(GPURenderPipeline), .{});
    };
};

pub const GPUSampler = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPUSampler);

        pub const Meta = struct {
            pub const name = "GPUSampler";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const label = bridge.accessor(deadGet(GPUSampler), deadSet(GPUSampler), .{});
    };
};

pub const GPUShaderModule = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPUShaderModule);

        pub const Meta = struct {
            pub const name = "GPUShaderModule";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const getCompilationInfo = bridge.function(deadCall(GPUShaderModule), .{ .arity = 0, .noop = true });
        pub const label = bridge.accessor(deadGet(GPUShaderModule), deadSet(GPUShaderModule), .{});
    };
};

pub const GPUTextureView = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(GPUTextureView);

        pub const Meta = struct {
            pub const name = "GPUTextureView";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const label = bridge.accessor(deadGet(GPUTextureView), deadSet(GPUTextureView), .{});
    };
};

pub const IdentityProvider = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(IdentityProvider);

        pub const Meta = struct {
            pub const name = "IdentityProvider";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const close = bridge.function(deadStatic(), .{ .static = true, .arity = 0, .noop = true });
        pub const getUserInfo = bridge.function(deadStatic(), .{ .static = true, .arity = 1, .noop = true });
        pub const resolve = bridge.function(deadStatic(), .{ .static = true, .arity = 1, .noop = true });
    };
};

pub const ImageBitmapRenderingContext = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(ImageBitmapRenderingContext);

        pub const Meta = struct {
            pub const name = "ImageBitmapRenderingContext";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const canvas = bridge.accessor(deadGet(ImageBitmapRenderingContext), null, .{});
        pub const transferFromImageBitmap = bridge.function(deadCall(ImageBitmapRenderingContext), .{ .arity = 1, .noop = true });
    };
};

pub const LaunchParams = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(LaunchParams);

        pub const Meta = struct {
            pub const name = "LaunchParams";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const files = bridge.accessor(deadGet(LaunchParams), null, .{});
        pub const targetURL = bridge.accessor(deadGet(LaunchParams), null, .{});
    };
};

pub const LaunchQueue = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(LaunchQueue);

        pub const Meta = struct {
            pub const name = "LaunchQueue";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const setConsumer = bridge.function(deadCall(LaunchQueue), .{ .arity = 1, .noop = true });
    };
};

pub const Lock = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(Lock);

        pub const Meta = struct {
            pub const name = "Lock";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const mode = bridge.accessor(deadGet(Lock), null, .{});
        pub const name = bridge.accessor(deadGet(Lock), null, .{});
    };
};

pub const MediaSourceHandle = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(MediaSourceHandle);

        pub const Meta = struct {
            pub const name = "MediaSourceHandle";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };
    };
};

pub const NavigationPrecommitController = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(NavigationPrecommitController);

        pub const Meta = struct {
            pub const name = "NavigationPrecommitController";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const addHandler = bridge.function(deadCall(NavigationPrecommitController), .{ .arity = 1, .noop = true });
        pub const redirect = bridge.function(deadCall(NavigationPrecommitController), .{ .arity = 1, .noop = true });
    };
};

pub const NotRestoredReasonDetails = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(NotRestoredReasonDetails);

        pub const Meta = struct {
            pub const name = "NotRestoredReasonDetails";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const reason = bridge.accessor(deadGet(NotRestoredReasonDetails), null, .{});
        pub const toJSON = bridge.function(deadCall(NotRestoredReasonDetails), .{ .arity = 0, .noop = true });
    };
};

pub const PaymentManager = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(PaymentManager);

        pub const Meta = struct {
            pub const name = "PaymentManager";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const enableDelegations = bridge.function(deadCall(PaymentManager), .{ .arity = 1, .noop = true });
        pub const userHint = bridge.accessor(deadGet(PaymentManager), deadSet(PaymentManager), .{});
    };
};

pub const PresentationReceiver = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(PresentationReceiver);

        pub const Meta = struct {
            pub const name = "PresentationReceiver";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const connectionList = bridge.accessor(deadGet(PresentationReceiver), null, .{});
    };
};

pub const PushSubscriptionOptions = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(PushSubscriptionOptions);

        pub const Meta = struct {
            pub const name = "PushSubscriptionOptions";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const applicationServerKey = bridge.accessor(deadGet(PushSubscriptionOptions), null, .{});
        pub const userVisibleOnly = bridge.accessor(deadGet(PushSubscriptionOptions), null, .{});
    };
};

pub const RTCCertificate = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(RTCCertificate);

        pub const Meta = struct {
            pub const name = "RTCCertificate";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const expires = bridge.accessor(deadGet(RTCCertificate), null, .{});
        pub const getFingerprints = bridge.function(deadCall(RTCCertificate), .{ .arity = 0, .noop = true });
    };
};

pub const ReportBody = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(ReportBody);

        pub const Meta = struct {
            pub const name = "ReportBody";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const toJSON = bridge.function(deadCall(ReportBody), .{ .arity = 0, .noop = true });
    };
};

pub const RestrictionTarget = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(RestrictionTarget);

        pub const Meta = struct {
            pub const name = "RestrictionTarget";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const fromElement = bridge.function(deadStatic(), .{ .static = true, .arity = 1, .noop = true });
    };
};

pub const SVGAnimatedAngle = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(SVGAnimatedAngle);

        pub const Meta = struct {
            pub const name = "SVGAnimatedAngle";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const animVal = bridge.accessor(deadGet(SVGAnimatedAngle), null, .{});
        pub const baseVal = bridge.accessor(deadGet(SVGAnimatedAngle), null, .{});
    };
};

pub const SVGAnimatedBoolean = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(SVGAnimatedBoolean);

        pub const Meta = struct {
            pub const name = "SVGAnimatedBoolean";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const animVal = bridge.accessor(deadGet(SVGAnimatedBoolean), null, .{});
        pub const baseVal = bridge.accessor(deadGet(SVGAnimatedBoolean), deadSet(SVGAnimatedBoolean), .{});
    };
};

pub const SVGAnimatedInteger = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(SVGAnimatedInteger);

        pub const Meta = struct {
            pub const name = "SVGAnimatedInteger";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const animVal = bridge.accessor(deadGet(SVGAnimatedInteger), null, .{});
        pub const baseVal = bridge.accessor(deadGet(SVGAnimatedInteger), deadSet(SVGAnimatedInteger), .{});
    };
};

pub const SVGAnimatedLengthList = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(SVGAnimatedLengthList);

        pub const Meta = struct {
            pub const name = "SVGAnimatedLengthList";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const animVal = bridge.accessor(deadGet(SVGAnimatedLengthList), null, .{});
        pub const baseVal = bridge.accessor(deadGet(SVGAnimatedLengthList), null, .{});
    };
};

pub const SVGAnimatedNumberList = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(SVGAnimatedNumberList);

        pub const Meta = struct {
            pub const name = "SVGAnimatedNumberList";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const animVal = bridge.accessor(deadGet(SVGAnimatedNumberList), null, .{});
        pub const baseVal = bridge.accessor(deadGet(SVGAnimatedNumberList), null, .{});
    };
};

pub const SVGAnimatedRect = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(SVGAnimatedRect);

        pub const Meta = struct {
            pub const name = "SVGAnimatedRect";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const animVal = bridge.accessor(deadGet(SVGAnimatedRect), null, .{});
        pub const baseVal = bridge.accessor(deadGet(SVGAnimatedRect), null, .{});
    };
};

pub const SharedStorageModifierMethod = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(SharedStorageModifierMethod);

        pub const Meta = struct {
            pub const name = "SharedStorageModifierMethod";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };
    };
};

pub const SyncManager = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(SyncManager);

        pub const Meta = struct {
            pub const name = "SyncManager";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const getTags = bridge.function(deadCall(SyncManager), .{ .arity = 0, .noop = true });
        pub const register = bridge.function(deadCall(SyncManager), .{ .arity = 1, .noop = true });
    };
};

pub const TextTrackCueList = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(TextTrackCueList);

        pub const Meta = struct {
            pub const name = "TextTrackCueList";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const getCueById = bridge.function(deadCall(TextTrackCueList), .{ .arity = 1, .noop = true });
        pub const length = bridge.accessor(deadGet(TextTrackCueList), null, .{});
    };
};

pub const TouchList = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(TouchList);

        pub const Meta = struct {
            pub const name = "TouchList";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const item = bridge.function(deadCall(TouchList), .{ .arity = 1, .noop = true });
        pub const length = bridge.accessor(deadGet(TouchList), null, .{});
    };
};

pub const TrustedHTML = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(TrustedHTML);

        pub const Meta = struct {
            pub const name = "TrustedHTML";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const toJSON = bridge.function(deadCall(TrustedHTML), .{ .arity = 0, .noop = true });
        pub const toString = bridge.function(deadCall(TrustedHTML), .{ .arity = 0, .noop = true });
    };
};

pub const TrustedScript = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(TrustedScript);

        pub const Meta = struct {
            pub const name = "TrustedScript";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const toJSON = bridge.function(deadCall(TrustedScript), .{ .arity = 0, .noop = true });
        pub const toString = bridge.function(deadCall(TrustedScript), .{ .arity = 0, .noop = true });
    };
};

pub const TrustedScriptURL = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(TrustedScriptURL);

        pub const Meta = struct {
            pub const name = "TrustedScriptURL";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const toJSON = bridge.function(deadCall(TrustedScriptURL), .{ .arity = 0, .noop = true });
        pub const toString = bridge.function(deadCall(TrustedScriptURL), .{ .arity = 0, .noop = true });
    };
};

pub const Viewport = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(Viewport);

        pub const Meta = struct {
            pub const name = "Viewport";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const segments = bridge.accessor(deadGet(Viewport), null, .{});
    };
};

pub const WebTransportBidirectionalStream = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(WebTransportBidirectionalStream);

        pub const Meta = struct {
            pub const name = "WebTransportBidirectionalStream";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const readable = bridge.accessor(deadGet(WebTransportBidirectionalStream), null, .{});
        pub const writable = bridge.accessor(deadGet(WebTransportBidirectionalStream), null, .{});
    };
};

pub const Worklet = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(Worklet);

        pub const Meta = struct {
            pub const name = "Worklet";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const addModule = bridge.function(deadCall(Worklet), .{ .arity = 1, .noop = true });
    };
};

pub const XRAnchor = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(XRAnchor);

        pub const Meta = struct {
            pub const name = "XRAnchor";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const anchorSpace = bridge.accessor(deadGet(XRAnchor), null, .{});
        pub const delete = bridge.function(deadCall(XRAnchor), .{ .arity = 0, .noop = true });
    };
};

pub const XRCamera = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(XRCamera);

        pub const Meta = struct {
            pub const name = "XRCamera";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const height = bridge.accessor(deadGet(XRCamera), null, .{});
        pub const width = bridge.accessor(deadGet(XRCamera), null, .{});
    };
};

pub const XRDOMOverlayState = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(XRDOMOverlayState);

        pub const Meta = struct {
            pub const name = "XRDOMOverlayState";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const @"type" = bridge.accessor(deadGet(XRDOMOverlayState), null, .{});
    };
};

pub const XRHitTestResult = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(XRHitTestResult);

        pub const Meta = struct {
            pub const name = "XRHitTestResult";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const createAnchor = bridge.function(deadCall(XRHitTestResult), .{ .arity = 0, .noop = true });
        pub const getPose = bridge.function(deadCall(XRHitTestResult), .{ .arity = 1, .noop = true });
    };
};

pub const XRHitTestSource = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(XRHitTestSource);

        pub const Meta = struct {
            pub const name = "XRHitTestSource";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const cancel = bridge.function(deadCall(XRHitTestSource), .{ .arity = 0, .noop = true });
    };
};

pub const XRPose = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(XRPose);

        pub const Meta = struct {
            pub const name = "XRPose";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const emulatedPosition = bridge.accessor(deadGet(XRPose), null, .{});
        pub const transform = bridge.accessor(deadGet(XRPose), null, .{});
    };
};

pub const XRSubImage = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(XRSubImage);

        pub const Meta = struct {
            pub const name = "XRSubImage";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const viewport = bridge.accessor(deadGet(XRSubImage), null, .{});
    };
};

pub const XRTransientInputHitTestResult = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(XRTransientInputHitTestResult);

        pub const Meta = struct {
            pub const name = "XRTransientInputHitTestResult";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const inputSource = bridge.accessor(deadGet(XRTransientInputHitTestResult), null, .{});
        pub const results = bridge.accessor(deadGet(XRTransientInputHitTestResult), null, .{});
    };
};

pub const XRTransientInputHitTestSource = struct {
    // Padding: a zero-size struct collides in the identity map.
    _pad: bool = false,

    pub const JsApi = struct {
        pub const bridge = js.Bridge(XRTransientInputHitTestSource);

        pub const Meta = struct {
            pub const name = "XRTransientInputHitTestSource";
            pub const prototype_chain = bridge.prototypeChain();
            pub var class_id: bridge.ClassId = undefined;
            pub const empty_with_no_proto = true;
        };

        pub const cancel = bridge.function(deadCall(XRTransientInputHitTestSource), .{ .arity = 0, .noop = true });
    };
};

/// Registered as one entry in bridge.PageJsApis via flattenTypes.
pub fn registerTypes() []const type {
    return &.{
        AnimationTimeline,
        AudioSinkInfo,
        AuthenticatorResponse,
        BackgroundFetchRecord,
        BluetoothUUID,
        CSSStyleValue,
        Credential,
        CropTarget,
        DOMRectList,
        DelegatedInkTrailPresenter,
        External,
        FencedFrameConfig,
        FetchLaterResult,
        FragmentDirective,
        GPUBindGroup,
        GPUBindGroupLayout,
        GPUCommandBuffer,
        GPUCompilationInfo,
        GPUComputePipeline,
        GPUDeviceLostInfo,
        GPUError,
        GPUExternalTexture,
        GPUPipelineLayout,
        GPURenderBundle,
        GPURenderPipeline,
        GPUSampler,
        GPUShaderModule,
        GPUTextureView,
        IdentityProvider,
        ImageBitmapRenderingContext,
        LaunchParams,
        LaunchQueue,
        Lock,
        MediaSourceHandle,
        NavigationPrecommitController,
        NotRestoredReasonDetails,
        PaymentManager,
        PresentationReceiver,
        PushSubscriptionOptions,
        RTCCertificate,
        ReportBody,
        RestrictionTarget,
        SVGAnimatedAngle,
        SVGAnimatedBoolean,
        SVGAnimatedInteger,
        SVGAnimatedLengthList,
        SVGAnimatedNumberList,
        SVGAnimatedRect,
        SharedStorageModifierMethod,
        SyncManager,
        TextTrackCueList,
        TouchList,
        TrustedHTML,
        TrustedScript,
        TrustedScriptURL,
        Viewport,
        WebTransportBidirectionalStream,
        Worklet,
        XRAnchor,
        XRCamera,
        XRDOMOverlayState,
        XRHitTestResult,
        XRHitTestSource,
        XRPose,
        XRSubImage,
        XRTransientInputHitTestResult,
        XRTransientInputHitTestSource,
    };
}
