// GENERATED by tools/gen_window_event_handlers.zig -- do not edit by hand.
//
// Window event-handler IDL attributes that Chrome exposes and that have no
// dispatch path here yet. They store and return a function so the property
// round-trips and enumerates exactly as Chrome's does; nothing fires them.
// See the generator for why this is a generated block and what it does not
// promise.

const js = @import("../js/js.zig");
const Window = @import("Window.zig");

/// One storage slot per attribute.
pub const Name = enum {
    onabort,
    onafterprint,
    onanimationcancel,
    onanimationend,
    onanimationiteration,
    onanimationstart,
    onappinstalled,
    onauxclick,
    onbeforeinput,
    onbeforeinstallprompt,
    onbeforematch,
    onbeforeprint,
    onbeforetoggle,
    onbeforeunload,
    onbeforexrselect,
    oncancel,
    oncanplay,
    oncanplaythrough,
    onchange,
    onclose,
    oncommand,
    oncontentvisibilityautostatechange,
    oncontextlost,
    oncontextmenu,
    oncontextrestored,
    oncuechange,
    ondblclick,
    ondevicemotion,
    ondeviceorientation,
    ondeviceorientationabsolute,
    ondrag,
    ondragend,
    ondragenter,
    ondragleave,
    ondragover,
    ondragstart,
    ondrop,
    ondurationchange,
    onemptied,
    onended,
    onformdata,
    ongamepadconnected,
    ongamepaddisconnected,
    ongotpointercapture,
    oninput,
    oninvalid,
    onkeydown,
    onkeypress,
    onkeyup,
    onlanguagechange,
    onloadeddata,
    onloadedmetadata,
    onloadstart,
    onlostpointercapture,
    onmessageerror,
    onmousedown,
    onmouseenter,
    onmouseleave,
    onmousemove,
    onmouseout,
    onmouseover,
    onmouseup,
    onmousewheel,
    onoffline,
    ononline,
    onpagehide,
    onpagereveal,
    onpageswap,
    onpause,
    onplay,
    onplaying,
    onpointercancel,
    onpointerdown,
    onpointerenter,
    onpointerleave,
    onpointermove,
    onpointerout,
    onpointerover,
    onpointerrawupdate,
    onpointerup,
    onprogress,
    onratechange,
    onreset,
    onscrollend,
    onscrollsnapchange,
    onscrollsnapchanging,
    onsearch,
    onsecuritypolicyviolation,
    onseeked,
    onseeking,
    onselect,
    onselectionchange,
    onselectstart,
    onslotchange,
    onstalled,
    onstorage,
    onsubmit,
    onsuspend,
    ontimeupdate,
    ontoggle,
    ontransitioncancel,
    ontransitionend,
    ontransitionrun,
    ontransitionstart,
    onunload,
    onvolumechange,
    onwaiting,
    onwebkitanimationend,
    onwebkitanimationiteration,
    onwebkitanimationstart,
    onwebkittransitionend,
    onwheel,
};

pub const count = @typeInfo(Name).@"enum".fields.len;

/// Backing store, one nullable callback per attribute.
pub const Store = [count]?js.Function.Global;
pub const empty: Store = @splat(null);

pub fn getter(comptime name: Name) fn (*const Window) ?js.Function.Global {
    return struct {
        fn get(self: *const Window) ?js.Function.Global {
            return self._event_handlers[@intFromEnum(name)];
        }
    }.get;
}

pub fn setter(comptime name: Name) fn (*Window, ?Window.FunctionSetter) void {
    return struct {
        fn set(self: *Window, value: ?Window.FunctionSetter) void {
            // Assigning a non-function clears the handler, matching the
            // 13 hand-written handlers and the IDL event-handler type.
            self._event_handlers[@intFromEnum(name)] = Window.getFunctionFromSetter(value);
        }
    }.set;
}
