//! Optional bridge to the locally installed Chrome ANGLE/Metal GLES backend.
//! The C side loads the libraries at runtime and returns null if unavailable.

pub const Context = opaque {};

pub extern fn lp_angle_create(width: u32, height: u32, webgl2: c_int) ?*Context;
pub extern fn lp_angle_destroy(context: *Context) void;
pub extern fn lp_angle_resize(context: *Context, width: u32, height: u32) c_int;
pub extern fn lp_angle_create_shader(context: *Context, shader_type: u32) u32;
pub extern fn lp_angle_shader_source(context: *Context, shader: u32, source: [*]const u8, length: c_int) void;
pub extern fn lp_angle_compile_shader(context: *Context, shader: u32) void;
pub extern fn lp_angle_shader_info_log(context: *Context, shader: u32, out: [*]u8, capacity: c_int) c_int;
pub extern fn lp_angle_shader_parameter(context: *Context, shader: u32, pname: u32) c_int;
pub extern fn lp_angle_create_program(context: *Context) u32;
pub extern fn lp_angle_attach_shader(context: *Context, program: u32, shader: u32) void;
pub extern fn lp_angle_detach_shader(context: *Context, program: u32, shader: u32) void;
pub extern fn lp_angle_link_program(context: *Context, program: u32) void;
pub extern fn lp_angle_validate_program(context: *Context, program: u32) void;
pub extern fn lp_angle_program_info_log(context: *Context, program: u32, out: [*]u8, capacity: c_int) c_int;
pub extern fn lp_angle_program_parameter(context: *Context, program: u32, pname: u32) c_int;
pub extern fn lp_angle_active_info(context: *Context, program: u32, index: u32, uniform: c_int, name: [*]u8, capacity: c_int, size: *c_int, info_type: *u32) c_int;
pub extern fn lp_angle_use_program(context: *Context, program: u32) void;
pub extern fn lp_angle_is_program(context: *Context, id: u32) c_int;
pub extern fn lp_angle_delete_program(context: *Context, id: u32) void;
pub extern fn lp_angle_is_shader(context: *Context, id: u32) c_int;
pub extern fn lp_angle_delete_shader(context: *Context, id: u32) void;
pub extern fn lp_angle_uniform_location(context: *Context, program: u32, name: [*:0]const u8) c_int;
pub extern fn lp_angle_uniform1f(context: *Context, location: c_int, x: f32) void;
pub extern fn lp_angle_uniform2f(context: *Context, location: c_int, x: f32, y: f32) void;
pub extern fn lp_angle_uniform3f(context: *Context, location: c_int, x: f32, y: f32, z: f32) void;
pub extern fn lp_angle_uniform4f(context: *Context, location: c_int, x: f32, y: f32, z: f32, w: f32) void;
pub extern fn lp_angle_uniform1i(context: *Context, location: c_int, x: c_int) void;
pub extern fn lp_angle_uniform2i(context: *Context, location: c_int, x: c_int, y: c_int) void;
pub extern fn lp_angle_uniform3i(context: *Context, location: c_int, x: c_int, y: c_int, z: c_int) void;
pub extern fn lp_angle_uniform4i(context: *Context, location: c_int, x: c_int, y: c_int, z: c_int, w: c_int) void;
pub extern fn lp_angle_create_buffer(context: *Context) u32;
pub extern fn lp_angle_bind_buffer(context: *Context, target: u32, buffer: u32) void;
pub extern fn lp_angle_is_buffer(context: *Context, id: u32) c_int;
pub extern fn lp_angle_delete_buffer(context: *Context, id: u32) void;
pub extern fn lp_angle_create_texture(context: *Context) u32;
pub extern fn lp_angle_bind_texture(context: *Context, target: u32, id: u32) void;
pub extern fn lp_angle_is_texture(context: *Context, id: u32) c_int;
pub extern fn lp_angle_delete_texture(context: *Context, id: u32) void;
pub extern fn lp_angle_active_texture(context: *Context, texture: u32) void;
pub extern fn lp_angle_tex_parameteri(context: *Context, target: u32, pname: u32, value: c_int) void;
pub extern fn lp_angle_tex_parameterf(context: *Context, target: u32, pname: u32, value: f32) void;
pub extern fn lp_angle_get_tex_parameter(context: *Context, target: u32, pname: u32) c_int;
pub extern fn lp_angle_tex_image2d(context: *Context, target: u32, level: c_int, internal_format: c_int, width: c_int, height: c_int, border: c_int, format: u32, pixel_type: u32, pixels: ?[*]const u8) void;
pub extern fn lp_angle_tex_sub_image2d(context: *Context, target: u32, level: c_int, x: c_int, y: c_int, width: c_int, height: c_int, format: u32, pixel_type: u32, pixels: [*]const u8) void;
pub extern fn lp_angle_pixel_storei(context: *Context, pname: u32, value: c_int) void;
pub extern fn lp_angle_create_framebuffer(context: *Context) u32;
pub extern fn lp_angle_bind_framebuffer(context: *Context, target: u32, id: u32) void;
pub extern fn lp_angle_check_framebuffer_status(context: *Context, target: u32) u32;
pub extern fn lp_angle_framebuffer_renderbuffer(context: *Context, target: u32, attachment: u32, renderbuffer_target: u32, id: u32) void;
pub extern fn lp_angle_framebuffer_texture2d(context: *Context, target: u32, attachment: u32, texture_target: u32, id: u32, level: c_int) void;
pub extern fn lp_angle_is_framebuffer(context: *Context, id: u32) c_int;
pub extern fn lp_angle_delete_framebuffer(context: *Context, id: u32) void;
pub extern fn lp_angle_create_renderbuffer(context: *Context) u32;
pub extern fn lp_angle_bind_renderbuffer(context: *Context, target: u32, id: u32) void;
pub extern fn lp_angle_renderbuffer_storage(context: *Context, target: u32, format: u32, width: c_int, height: c_int) void;
pub extern fn lp_angle_get_renderbuffer_parameter(context: *Context, target: u32, pname: u32) c_int;
pub extern fn lp_angle_is_renderbuffer(context: *Context, id: u32) c_int;
pub extern fn lp_angle_delete_renderbuffer(context: *Context, id: u32) void;
pub extern fn lp_angle_buffer_data(context: *Context, target: u32, data: ?[*]const u8, length: usize, usage: u32) void;
pub extern fn lp_angle_attrib_location(context: *Context, program: u32, name: [*:0]const u8) c_int;
pub extern fn lp_angle_enable_vertex_attrib(context: *Context, index: u32) void;
pub extern fn lp_angle_vertex_attrib_pointer(context: *Context, index: u32, size: c_int, value_type: u32, normalized: c_int, stride: c_int, offset: usize) void;
pub extern fn lp_angle_viewport(context: *Context, x: c_int, y: c_int, width: c_int, height: c_int) void;
pub extern fn lp_angle_draw_arrays(context: *Context, mode: u32, first: c_int, count: c_int) void;
pub extern fn lp_angle_clear_color(context: *Context, red: f32, green: f32, blue: f32, alpha: f32) void;
pub extern fn lp_angle_clear(context: *Context, mask: u32) void;
pub extern fn lp_angle_read_pixels(context: *Context, x: c_int, y: c_int, width: c_int, height: c_int, out: [*]u8) c_int;
pub extern fn lp_angle_get_error(context: *Context) u32;
