//! Emits the Window event-handler IDL attributes that Chrome exposes and we
//! do not, as Zig source for `src/browser/webapi/window_event_handlers.zig`.
//!
//! WHY THESE EXIST AS A GENERATED BLOCK
//!
//! Chrome 151 puts 125 `onXxx` accessors on `window`; we had 13. The other 112
//! are not interfaces, just IDL attributes, and every one of them carries the
//! identical descriptor — `accessor e1c1w0`, enumerable and configurable with
//! no writable flag — which is what `bridge.accessor(get, set, .{})` already
//! produces for the 13 we had. Verified against a live Chrome census:
//! `browser-research/chrome/js/census.json`.
//!
//! They matter because `Object.getOwnPropertyNames(window)` is a fingerprint.
//! Chrome reports 1243 own properties, we reported 538; these 112 are the
//! single largest uniform block of that gap, and the cheapest to close.
//!
//! Zig cannot synthesise `pub const` declarations at comptime — `@Type` builds
//! fields, not decls, and `JsApi` is walked with `@typeInfo(...).@"struct".decls`
//! — so the declarations have to exist in source. Hence generation rather than
//! an `inline for`.
//!
//! WHAT THESE HANDLERS DO
//!
//! Nothing, deliberately. They store a function and hand the same one back, so
//! the property round-trips as Chrome's does and shows up in an enumeration.
//! No event is dispatched to them. That is strictly better than absence -- the
//! property previously did not exist at all -- but it is NOT an implementation:
//! a page that sets `window.ondevicemotion` and waits for a motion event waits
//! forever, exactly as it does today. Handlers get promoted out of this list as
//! their events become real; the 13 hand-written ones in Window.zig are the
//! ones that already dispatch.
//!
//! The matching `pub const` declarations live in Window.JsApi, because a
//! [Global] interface's members have to be real declarations there. Keep the
//! two in step: regenerate this file and re-emit that block together.
//!
//! Regenerate when Chrome adds attributes: re-run the census, diff, rerun this.
//!
//! Usage: gen_window_event_handlers <names-file> <out-dir>
//!   names-file: one attribute name per line, as emitted by the census diff.

const std = @import("std");

var io_threaded: std.Io.Threaded = .init_single_threaded;
const io: std.Io = io_threaded.io();

const header =
    \\// GENERATED by tools/gen_window_event_handlers.zig -- do not edit by hand.
    \\//
    \\// Window event-handler IDL attributes that Chrome exposes and that have no
    \\// dispatch path here yet. They store and return a function so the property
    \\// round-trips and enumerates exactly as Chrome's does; nothing fires them.
    \\// See the generator for why this is a generated block and what it does not
    \\// promise.
    \\
    \\const js = @import("../js/js.zig");
    \\const Window = @import("Window.zig");
    \\
    \\/// One storage slot per attribute.
    \\pub const Name = enum {
    \\
;

const middle =
    \\};
    \\
    \\pub const count = @typeInfo(Name).@"enum".fields.len;
    \\
    \\/// Backing store, one nullable callback per attribute.
    \\pub const Store = [count]?js.Function.Global;
    \\pub const empty: Store = @splat(null);
    \\
    \\pub fn getter(comptime name: Name) fn (*const Window) ?js.Function.Global {
    \\    return struct {
    \\        fn get(self: *const Window) ?js.Function.Global {
    \\            return self._event_handlers[@intFromEnum(name)];
    \\        }
    \\    }.get;
    \\}
    \\
    \\pub fn setter(comptime name: Name) fn (*Window, ?Window.FunctionSetter) void {
    \\    return struct {
    \\        fn set(self: *Window, value: ?Window.FunctionSetter) void {
    \\            // Assigning a non-function clears the handler, matching the
    \\            // 13 hand-written handlers and the IDL event-handler type.
    \\            self._event_handlers[@intFromEnum(name)] = Window.getFunctionFromSetter(value);
    \\        }
    \\    }.set;
    \\}
    \\
;

pub fn main(init: std.process.Init) !void {
    var gpa_state: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa_state.deinit();
    const gpa = gpa_state.allocator();

    var args = std.process.Args.Iterator.init(init.minimal.args);
    _ = args.next(); // argv[0]
    const names_path = args.next() orelse return error.MissingNamesFile;
    const out_dir_path = args.next() orelse return error.MissingOutputDir;

    const cwd = std.Io.Dir.cwd();
    const raw = try cwd.readFileAlloc(io, names_path, gpa, .limited(1 << 20));
    defer gpa.free(raw);

    var names: std.ArrayList([]const u8) = .empty;
    defer names.deinit(gpa);
    var it = std.mem.tokenizeAny(u8, raw, "\r\n");
    while (it.next()) |line| {
        const name = std.mem.trim(u8, line, " \t");
        if (name.len == 0) continue;
        // Defend against anything that is not a plain identifier reaching the
        // emitted source.
        for (name) |c| {
            if (!std.ascii.isLower(c) and !std.ascii.isDigit(c)) {
                std.debug.print("gen_window_event_handlers: rejecting {s}\n", .{name});
                return error.BadAttributeName;
            }
        }
        try names.append(gpa, name);
    }

    var out: std.ArrayList(u8) = .empty;
    defer out.deinit(gpa);

    try out.appendSlice(gpa, header);
    for (names.items) |name| {
        try out.appendSlice(gpa, "    ");
        try out.appendSlice(gpa, name);
        try out.appendSlice(gpa, ",\n");
    }
    try out.appendSlice(gpa, middle);

    var out_dir = try cwd.openDir(io, out_dir_path, .{});
    defer out_dir.close(io);
    try out_dir.writeFile(io, .{ .sub_path = "window_event_handlers.zig", .data = out.items });

    std.debug.print("gen_window_event_handlers: emitted {d} attributes\n", .{names.items.len});
}
