#!/usr/bin/env python3
"""Emit shape-only WebIDL interface objects that Chrome exposes and we do not.

WHY SHAPE-ONLY IS COMPLETE FOR THESE, NOT A COMPROMISE

Every interface emitted here is one Chrome refuses to construct:

    new CSSFontFaceRule()
    -> TypeError: Failed to construct 'CSSFontFaceRule': Illegal constructor

So no script can ever obtain an instance. And without an instance the members
are unreachable too -- reading a prototype accessor with the prototype itself
as the receiver throws:

    CSSFontFaceRule.prototype.style
    -> TypeError: Illegal invocation

Measured in Chrome 151. That leaves exactly one observable surface: the
*shape*. Constructor name, arity and `toString()`; the prototype's member
names and their descriptors; the prototype's parent; the static members. All
of that we can reproduce exactly. Behaviour cannot be observed, so there is no
behaviour to get wrong -- which is what makes generating these safe, and why
the same trick must NOT be extended to constructible interfaces without
thinking again.

WHY PYTHON AND NOT A tools/*.zig

The other generators in tools/ run inside build.zig and rewrite vendored C.
This one consumes a 100 KB JSON spec scraped from a live Chrome and emits
committed Zig source, so it never runs during a build and its language is
invisible to the build graph. Zig's JSON handling would add risk for no gain.

WHAT IT DOES NOT DO

Nothing here implements an API. `window.CSSFontFaceRule` becomes an interface
object of the right shape; it does not make CSS font-face rules work. Members
are declared with `.noop = true` (functions) or a dead getter (accessors) that
can never be invoked. If one of these interfaces ever becomes constructible,
its entry must move out of this generator and get a real implementation.

Regenerate:
    python3 tools/gen_webidl_interfaces.py tools/data/webidl-interfaces.json \\
        src/browser/webapi/generated_interfaces.zig
"""
import json
import sys

# Zig keywords and primitive type names. A WebIDL member called `type` or
# `error` is a legal JS name but not a legal bare Zig identifier, so it is
# emitted as @"type". The decl name is unchanged, so the JS-visible name --
# which the bridge takes from the declaration -- stays correct.
ZIG_RESERVED = {
    "addrspace", "align", "allowzero", "and", "anyframe", "anytype", "asm",
    "async", "await", "break", "callconv", "catch", "comptime", "const",
    "continue", "defer", "else", "enum", "errdefer", "error", "export",
    "extern", "fn", "for", "if", "inline", "linksection", "noalias",
    "noinline", "noreturn", "nosuspend", "opaque", "or", "orelse", "packed",
    "pub", "resume", "return", "struct", "suspend", "switch", "test",
    "threadlocal", "try", "union", "unreachable", "usingnamespace", "var",
    "volatile", "while",
    "anyerror", "anyopaque", "bool", "c_char", "c_int", "c_long",
    "c_longdouble", "c_longlong", "c_short", "c_uint", "c_ulong",
    "c_ulonglong", "c_ushort", "comptime_float", "comptime_int", "f16", "f32",
    "f64", "f80", "f128", "false", "isize", "null", "true", "type", "undefined",
    "usize", "void",
}


def zig_ident(name):
    if name in ZIG_RESERVED or not name.isidentifier():
        return f'@"{name}"'
    return name

HEADER = '''// GENERATED by tools/gen_webidl_interfaces.py -- do not edit by hand.
//
// Shape-only WebIDL interface objects. Every one of these is an interface
// Chrome refuses to construct ("Illegal constructor"), so no instance can
// exist and no member can ever be invoked. The observable surface is the
// shape alone -- constructor name/arity, prototype member names and their
// descriptors, prototype parent, statics -- and that is what this reproduces.
//
// These are NOT implementations. See the generator for the reasoning and for
// what has to change if any of them becomes constructible.

const js = @import("../js/js.zig");

// Dead member bodies. Unreachable by construction: reaching them would need an
// instance, and the constructor throws. The types are irrelevant for the same
// reason -- only the descriptor shape they produce is observable.
fn deadGet(comptime T: type) fn (*const T) ?u32 {
    return struct {
        fn get(_: *const T) ?u32 {
            return null;
        }
    }.get;
}

fn deadSet(comptime T: type) fn (*T, ?u32) void {
    return struct {
        fn set(_: *T, _: ?u32) void {}
    }.set;
}

fn deadCall(comptime T: type) fn (*const T) void {
    return struct {
        fn call(_: *const T) void {}
    }.call;
}

fn deadStatic() fn () void {
    return struct {
        fn call() void {}
    }.call;
}
'''


def emit_interface(name, spec):
    out = [f'\npub const {name} = struct {{']
    out.append('    // Padding: a zero-size struct collides in the identity map.')
    out.append('    _pad: bool = false,')
    out.append('')
    out.append('    pub const JsApi = struct {')
    out.append(f'        pub const bridge = js.Bridge({name});')
    out.append('')
    out.append('        pub const Meta = struct {')
    out.append(f'            pub const name = "{name}";')
    out.append('            pub const prototype_chain = bridge.prototypeChain();')
    out.append('            pub var class_id: bridge.ClassId = undefined;')
    out.append('            pub const empty_with_no_proto = true;')
    out.append('        };')

    members = spec.get('members', {})
    if members:
        out.append('')
    for member, m in sorted(members.items()):
        if m['kind'] == 'accessor':
            setter = f'deadSet({name})' if m.get('set') else 'null'
            out.append(
                f'        pub const {zig_ident(member)} = bridge.accessor('
                f'deadGet({name}), {setter}, .{{}});'
            )
        else:
            out.append(
                f'        pub const {zig_ident(member)} = bridge.function('
                f'deadCall({name}), .{{ .arity = {m["arity"]}, .noop = true }});'
            )

    statics = spec.get('staticSpecs', {})
    if statics:
        out.append('')
        for member, m in sorted(statics.items()):
            out.append(
                f'        pub const {zig_ident(member)} = bridge.function('
                f'deadStatic(), .{{ .static = true, .arity = {m["arity"]}, '
                f'.noop = true }});'
            )

    out.append('    };')
    out.append('};')
    return '\n'.join(out)


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    spec_path, out_path = sys.argv[1], sys.argv[2]
    spec = json.load(open(spec_path))

    names = sorted(spec)
    for name in names:
        if not name.isidentifier():
            raise SystemExit(f'refusing to emit non-identifier interface: {name!r}')

    parts = [HEADER]
    for name in names:
        parts.append(emit_interface(name, spec[name]))

    parts.append('\n/// Registered as one entry in bridge.PageJsApis via flattenTypes.')
    parts.append('pub fn registerTypes() []const type {')
    parts.append('    return &.{')
    for name in names:
        parts.append(f'        {name},')
    parts.append('    };')
    parts.append('}\n')

    open(out_path, 'w').write('\n'.join(parts))

    members = sum(len(spec[n].get('members', {})) for n in names)
    statics = sum(len(spec[n].get('staticSpecs', {})) for n in names)
    print(f'emitted {len(names)} interfaces, {members} members, {statics} statics -> {out_path}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
